- filesystem: "root"
  path: /etc/kubernetes/kubeconfig.yaml
  mode: 0644
  contents:
    inline: |
      apiVersion: v1
      kind: Config
      clusters:
      - name: local
        cluster:
          server: {kubeAPIServer}
          certificate-authority: /etc/kubernetes/ssl/ca.pem
      users:
      - name: kubelet
        user:
          client-certificate: /etc/kubernetes/ssl/{hostname}.pem
          client-key: /etc/kubernetes/ssl/{hostname}-key.pem
      contexts:
      - context:
          cluster: local
          user: kubelet
        name: kubelet-context
      current-context: kubelet-context
