- filesystem: "root"
  path: "/etc/kube-proxy/kubeconfig.yaml"
  mode: 0644
  contents:
    inline: |
      apiVersion: v1
      kind: Config
      clusters:
      - name: local
        cluster:
          server: {kubeAPIServer}
          certificate-authority: /run/secrets/kubernetes.io/serviceaccount/ca.crt
      users:
      - name: kube-proxy
        user:
          tokenFile: /run/secrets/kubernetes.io/serviceaccount/token
      contexts:
      - context:
          cluster: local
          user: kube-proxy
        name: kubelet-context
      current-context: kubelet-context
